 # Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Velocity Controllers -----------------------------------------
front_left_robile_drive_left_hub_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: front_left_robile_drive_left_hub_wheel_joint
  pid: {p: 100.0, i: 10.0, d: 0.01}
front_left_robile_drive_right_hub_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: front_left_robile_drive_right_hub_wheel_joint
  pid: {p: 100.0, i: 10.0, d: 0.01}


rear_left_robile_drive_left_hub_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_left_robile_drive_left_hub_wheel_joint
  pid: {p: 100.0, i: 10.0, d: 0.01}
rear_left_robile_drive_right_hub_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_left_robile_drive_right_hub_wheel_joint
  pid: {p: 100.0, i: 10.0, d: 0.01}


rear_right_robile_drive_left_hub_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_right_robile_drive_left_hub_wheel_joint
  pid: {p: 100.0, i: 10.0, d: 0.01}
rear_right_robile_drive_right_hub_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: rear_right_robile_drive_right_hub_wheel_joint
  pid: {p: 100.0, i: 10.0, d: 0.01}


front_right_robile_drive_left_hub_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: front_right_robile_drive_left_hub_wheel_joint
  pid: {p: 100.0, i: 10.0, d: 0.01}
front_right_robile_drive_right_hub_wheel_controller:
  type: effort_controllers/JointVelocityController
  joint: front_right_robile_drive_right_hub_wheel_joint
  pid: {p: 100.0, i: 10.0, d: 0.01}

# Position Controllers -----------------------------------------
front_left_robile_drive_pivot_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_robile_drive_pivot_joint
  pid: {p: 10.0, i: 1.0, d: 0.01}

rear_left_robile_drive_pivot_controller:
  type: effort_controllers/JointPositionController
  joint: rear_left_robile_drive_pivot_joint
  pid: {p: 10.0, i: 1.0, d: 0.01}

rear_right_robile_drive_pivot_controller:
  type: effort_controllers/JointPositionController
  joint: rear_right_robile_drive_pivot_joint
  pid: {p: 10.0, i: 1.0, d: 0.01}

front_right_robile_drive_pivot_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_robile_drive_pivot_joint
  pid: {p: 10.0, i: 1.0, d: 0.01}
